import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./footer";
import { getServerSession } from "next-auth"
import { authOptions } from "@/pages/api/auth/[...nextauth]"
import { Provider } from 'react-redux';
import store from '@/app/store'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {

  let session = await getServerSession(authOptions)
  // const { setUserInfo } = userData();
  // setUserInfo(session);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} d-flex flex-column min-vh-100`}>
        {/* <Provider store={store}> */}
          <Navbar session={session}></Navbar>
          {children}
          <Footer></Footer>
        {/* </Provider> */}
      </body>
    </html>
  );
}
